site_name: jsPsych in Qualtrics Tutorial Series
theme: readthedocs
site_url: 'https://kywch.github.io/jsPsych-in-Qualtrics/'
repo_url: 'https://github.com/kywch/jsPsych-in-Qualtrics/'
repo_name: 'kywch/jsPsych-in-Qualtrics'
edit_uri: ''
docs_dir: 'mkdocs'
nav:
- Introduction: 'index.md'
- Part 1. The Basics:
  - Hosting jsPsych: 'github-pages.md'
  - Embedding Hello World!: 'hello-world.md'
  - Saving Data with PHP: 'save-php.md'
  - Saving Data to your Dropbox: 'save-dropbox.md'
  - Recruiting Participants: 'participants.md'
- Part 2. Case studies:
  - Embedding Reaction-Time Task: 'rt-task.md'
  - Embedding Flanker Task: 'flanker.md'
  - Embedding Choose-And-Solve Task: 'choose-and-solve.md'  
  - Embedding Stop Signal Task (STOP-IT): 'stop-it.md'
  - Embedding Quick Audio Test: 'audio-test.md'
  - Embedding Mood Induction: 'mood-induction.md'
#  - Embedding Reactive AGression Task: 'rc-rage.md'
#site_author: 'Kyoung Whan Choe'
site_description: 'Step-by-step tutorials and examples on adding jsPsych cognitive tasks to Qualtrics'
copyright: 'Copyright &copy; 2020-2021 <a href="https://kywch.github.io/" target="_blank">Kyoung Whan Choe</a>. '
google_analytics:
- 'UA-102316-3'
- 'auto'
